<%@ Page Language="C#" AutoEventWireup="true" CodeFile="ASPDB_Customer_GridView_Editing.aspx.cs" Inherits="Ado.net.ASPDB_Customer_GridView_Editing" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="false" Caption="Customer Editing" HorizontalAlign="Center" OnRowEditing="GridView1_RowEditing" OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowDeleting="GridView1_RowDeleting" OnRowUpdating="GridView1_RowUpdating">
                <%-- AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" --%>
                <%--this is on option row editing and delete--%>
                <HeaderStyle BackColor="Yellow" ForeColor="Red" />
                <RowStyle ForeColor="Tan" BackColor="Teal" />
                <AlternatingRowStyle ForeColor="Teal" BackColor="Tan" />
                <EditRowStyle BackColor="LightCoral" ForeColor="WindowFrame" />
                <Columns>
                           <asp:BoundField HeaderText="Customer Id" DataField="Custid" ReadOnly="true" ItemStyle-HorizontalAlign="Center" />
                            <asp:BoundField HeaderText="Names" DataField="Names" />
                            <asp:BoundField HeaderText="Balance" DataField="Balance" ItemStyle-HorizontalAlign="Right" />
                            <asp:BoundField HeaderText="City" DataField="City" />
                            <asp:CheckBoxField HeaderText="Is-Active" DataField="Status" ItemStyle-HorizontalAlign="Center" ReadOnly="true" />
                            <%-- <asp:CommandField HeaderText="Action" ShowEditButton="true" ShowDeleteButton="true" ItemStyle-BackColor="White" ItemStyle-ForeColor="Blue" />--%> <%--second option--%>
                     <asp:TemplateField HeaderText="Actions" ItemStyle-BackColor="White" ItemStyle-ForeColor="Blue">
                            <ItemTemplate>
                                    <asp:LinkButton ID="btnEdit" runat="server" Text="Edit" CommandName="Edit" />
                                    <asp:LinkButton ID="btnDelete" runat="server" Text="Delete" CommandName="Delete" OnClientClick="return confirm('Are you sure of deleting the current record?')" />
                             </ItemTemplate>
                         <EditItemTemplate>
                                <asp:LinkButton ID="btnUpdate" runat="server" Text="Update" CommandName="Update" />
                                <asp:LinkButton ID="LinkCancel" runat="server" Text="Cancel" CommandName="Cancel" />
                          </EditItemTemplate>
                     </asp:TemplateField>

                </Columns>
            </asp:GridView>

        </div>
    </form>
</body>
</html>

<%--spacial proferty commandname="which event"--%>
<%--command name is wrong binding will not happen--%>
